# Generated by Django 4.0.3 on 2022-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='applied_on',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description_preview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='excitement',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='follow_up',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='img_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='rank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
