# Generated by Django 4.0.3 on 2022-03-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_job_additional_details_alter_job_applied_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='follow_up',
            field=models.DateField(blank=True, null=True),
        ),
    ]
